# modality_agreement_analysis.py
# Calculates agreement between Textual and Visual modalities.
# Consumes the *_labeled.csv outputs from finetuned_analysis.py.
# Provides per-file, per-continent, and US vs China breakdowns.

import os
import glob
import pandas as pd
import numpy as np
import warnings
from scipy.stats import spearmanr
from sklearn.metrics import cohen_kappa_score

warnings.filterwarnings("ignore")

# ══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════
PROJECT_ROOT = (
    "/Users/davidluu/Library/Mobile Documents/com~apple~CloudDocs/ACADEMIA/me/"
    "Publications/Securitizing the Global South in a Bipolar World Order "
    "A Multimodal Analysis of US and Chinese News Media"
)

# Input comes from the results folder generated by finetuned_analysis.py
INPUT_DIR = os.path.join(PROJECT_ROOT, "results_final_analysis")
REPORT_PATH = os.path.join(INPUT_DIR, "modality_agreement_detailed_report.txt")

# The 16 target files to ensure we are only analyzing the relevant data
TARGET_FILES = {
    "cluster_2_g_zh_hy_labeled.csv", "cluster_2_g_us_hy_labeled.csv",
    "cluster_2_f_zh_hy_labeled.csv", "cluster_2_f_us_hy_labeled.csv",
    "cluster_2_e_zh_hy_labeled.csv", "cluster_2_e_us_hy_labeled.csv",
    "cluster_2_d_zh_hy_labeled.csv", "cluster_2_d_us_hy_labeled.csv",
    "cluster_2_c_zh_hy_labeled.csv", "cluster_2_c_us_hy_labeled.csv",
    "cluster_2_b_zh_hy_labeled.csv", "cluster_2_b_us_hy_labeled.csv",
    "cluster_2_a_zh_hy_labeled.csv", "cluster_2_a_us_hy_labeled.csv",
    "cluster_1_a_gn_hy_labeled.csv", "cluster_1_a_gs_hy_labeled.csv"
}

# ══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ══════════════════════════════════════════════════════════════════════════════

def get_group(fname: str) -> str:
    f = fname.lower()
    if "_gs_" in f: return "Global South"
    if "_gn_" in f: return "Global North"
    if "_us_" in f: return "USA"
    if "_zh_" in f: return "China"
    return "Other"

def interpret_kappa(k):
    if k > 0.8: return "Almost Perfect"
    if k > 0.6: return "Substantial"
    if k > 0.4: return "Moderate"
    if k > 0.2: return "Fair"
    if k > 0: return "Slight"
    return "Poor/None"

# ══════════════════════════════════════════════════════════════════════════════
# MAIN ANALYSIS
# ══════════════════════════════════════════════════════════════════════════════

def run_analysis():
    labeled_paths = glob.glob(os.path.join(INPUT_DIR, "*_labeled.csv"))
    valid_paths = [p for p in labeled_paths if os.path.basename(p) in TARGET_FILES]
    
    if not valid_paths:
        print(f"No target labeled files found in {INPUT_DIR}. Run 'finetuned_analysis.py' first.")
        return

    print(f"Analyzing modality agreement for {len(valid_paths)} files...")
    
    file_stats = []
    all_data_frames = []

    for path in valid_paths:
        fname = os.path.basename(path)
        df = pd.read_csv(path)
        
        # Filter for rows where both modalities were successfully coded
        # (Exclude "not applicable" visual scores which are NaN)
        valid_df = df.dropna(subset=["Score_Text", "Score_Visual"]).copy()
        
        n_valid = len(valid_df)
        group = get_group(fname)
        
        rho, p_val, kappa = np.nan, np.nan, np.nan
        
        if n_valid > 5:
            # 1. Spearman's Rho (Numeric Correlation)
            if valid_df["Score_Text"].std() > 0 and valid_df["Score_Visual"].std() > 0:
                rho, p_val = spearmanr(valid_df["Score_Text"], valid_df["Score_Visual"])
            
            # 2. Cohen's Kappa (Categorical Agreement)
            kappa = cohen_kappa_score(valid_df["Securitization_Text"], valid_df["Securitization_Visual"])
        
        # Calculate Modality Gap (Text Mean - Visual Mean)
        txt_m = valid_df["Score_Text"].mean()
        vis_m = valid_df["Score_Visual"].mean()
        gap = txt_m - vis_m if (not np.isnan(txt_m) and not np.isnan(vis_m)) else np.nan

        file_stats.append({
            "File": fname,
            "Group": group,
            "N": n_valid,
            "Text_Mean": txt_m,
            "Visual_Mean": vis_m,
            "Modality_Gap": gap,
            "Spearman_Rho": rho,
            "Kappa": kappa
        })
        
        all_data_frames.append(valid_df)

    # ── Reporting ──────────────────────────────────────────────────────────────
    stats_df = pd.DataFrame(file_stats).sort_values(by="File")
    
    print("\n" + "="*85)
    print(f"{'FILE-BY-FILE MODALITY COMPARISON':^85}")
    print("="*85)
    print(f"{'Filename':<30} | {'N':<4} | {'Txt':<5} | {'Vis':<5} | {'Gap':<6} | {'Rho':<6} | {'Kappa'}")
    print("-" * 85)
    
    for _, r in stats_df.iterrows():
        rho_s = f"{r['Spearman_Rho']:.2f}" if not np.isnan(r['Spearman_Rho']) else "N/A"
        kap_s = f"{r['Kappa']:.2f}" if not np.isnan(r['Kappa']) else "N/A"
        print(f"{r['File'][:30]:<30} | {int(r['N']):<4} | {r['Text_Mean']:>5.2f} | {r['Visual_Mean']:>5.2f} | {r['Modality_Gap']:>6.2f} | {rho_s:<6} | {kap_s}")

    # ── Group Breakdowns (RQ1 and RQ2) ────────────────────────────────────────
    print("\n" + "="*85)
    print(f"{'GROUP BREAKDOWN: CONTINENTS & POWERS':^85}")
    print("="*85)
    
    group_agg = stats_df.groupby("Group").agg({
        "Text_Mean": "mean",
        "Visual_Mean": "mean",
        "Modality_Gap": "mean",
        "Spearman_Rho": "mean",
        "Kappa": "mean"
    }).round(3)
    
    print(group_agg)

    # ── Overall Corpus Summary ────────────────────────────────────────────────
    full_corpus = pd.concat(all_data_frames, ignore_index=True)
    total_rho, _ = spearmanr(full_corpus["Score_Text"], full_corpus["Score_Visual"])
    total_kappa = cohen_kappa_score(full_corpus["Securitization_Text"], full_corpus["Securitization_Visual"])
    
    print("\n" + "="*85)
    print(f"{'TOTAL CORPUS AGREEMENT (RQ3)':^85}")
    print("="*85)
    print(f"Total Multimodal Samples: {len(full_corpus)}")
    print(f"Overall Spearman's Rho:   {total_rho:.4f}")
    print(f"Overall Cohen's Kappa:    {total_kappa:.4f} ({interpret_kappa(total_kappa)})")
    print("="*85)

    # Save to file
    with open(REPORT_PATH, "w") as f:
        f.write("Modality Agreement Detailed Analysis\n")
        f.write("====================================\n\n")
        f.write("PER-FILE ANALYSIS:\n")
        f.write(stats_df.to_string(index=False) + "\n\n")
        f.write("GROUP ANALYSIS:\n")
        f.write(group_agg.to_string() + "\n\n")
        f.write(f"OVERALL CORPUS AGREEMENT:\n")
        f.write(f"Spearman Rho: {total_rho:.4f}\n")
        f.write(f"Cohen Kappa:  {total_kappa:.4f}\n")

    print(f"\nDetailed report saved to: {REPORT_PATH}")

if __name__ == "__main__":
    run_analysis()